Repository CartoDB/documentation, pull requests merged in 2021-11, with the labels that each got.

#173 Documentation improvements
  app/content/carto-user-manual/_index.md
  app/content/carto-user-manual/applications/accessing-applications.md
  app/content/carto-user-manual/connections/introduction.md
  app/content/carto-user-manual/data-explorer/deleting-data.md
  app/content/carto-user-manual/data-explorer/importing-data.md
  app/content/carto-user-manual/data-explorer/introduction.md
  app/content/carto-user-manual/developers/carto-for-developers.md
  app/content/carto-user-manual/maps/add-source.md
  app/content/carto-user-manual/maps/introduction.md
  app/content/carto-user-manual/maps/map-settings.md
  app/content/carto-user-manual/settings/introduction.md
  app/static/img/cloud-native-workspace/data-explorer/de_dataset_creation_error_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_dataset_creation_error_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_delete_table.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_confirmation_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_confirmation_url_.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_data_icon.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_dataset_file_continue_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_dataset_file_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_land.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_populated_places.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_remote.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_select_file_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_select_file_local_continue.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_select_file_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_selected_file_continue_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_imported_successfully_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_imported_successfully_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_importing_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_importing_local_to_cartodw.png
  app/static/img/cloud-native-workspace/data-explorer/de_importing_url.png
  app/static/img/cloud-native-workspace/data-explorer/de_importing_url_to_cartodw.png
  app/static/img/cloud-native-workspace/data-explorer/de_quick_actions_table_menu.png
  app/static/img/cloud-native-workspace/data-explorer/de_quick_actions_tileset_menu.png
  app/static/img/cloud-native-workspace/data-explorer/de_view_error_info_local.png
  app/static/img/cloud-native-workspace/data-explorer/de_view_error_info_url.png
  app/static/img/cloud-native-workspace/maps/map_add_source_a_custom_query.png
  app/static/img/cloud-native-workspace/maps/map_add_source_an_analysis_query.png
  app/static/img/cloud-native-workspace/maps/map_add_source_import_a_file.png
  app/static/img/cloud-native-workspace/maps/map_add_source_importing_local_file.png
  app/static/img/cloud-native-workspace/maps/map_add_source_select_a_bq_connection.png
  app/static/img/cloud-native-workspace/maps/map_add_source_select_a_connection.png
  app/static/img/cloud-native-workspace/maps/map_add_source_select_table.png
  app/static/img/cloud-native-workspace/maps/map_add_source_table.png
  app/static/img/cloud-native-workspace/maps/map_import_confirmation_local_file.png
  app/static/img/cloud-native-workspace/maps/map_import_confirmation_remote_url.png
  app/static/img/cloud-native-workspace/maps/map_import_local.png
  app/static/img/cloud-native-workspace/maps/map_import_local_file.png
  app/static/img/cloud-native-workspace/maps/map_import_local_file_continue.png
  app/static/img/cloud-native-workspace/maps/map_import_remote.png
  app/static/img/cloud-native-workspace/maps/map_import_remote_url.png
  app/static/img/cloud-native-workspace/maps/map_import_remote_url_continue.png
  app/static/img/cloud-native-workspace/maps/map_import_rivers.png
  app/static/img/cloud-native-workspace/maps/map_import_urban_areas.png
  app/static/img/cloud-native-workspace/maps/map_importing_local_file.png
  app/static/img/cloud-native-workspace/maps/map_importing_remote_url.png
Labels: documentation, do-not-merge

#180 Add viewportFeaturesDebounceTimeout prop in useCartoLayerProps reference
  app/content/react/library-reference/api.md
Labels: do-not-merge

#187 Update documentation for private maps
  app/content/carto-user-manual/maps/publishing-and-sharing-maps.md
  app/content/carto-user-manual/overview/getting-started.md
  app/static/img/cloud-native-workspace/maps/map_publish_map.png
  app/static/img/cloud-native-workspace/maps/map_publish_map_last_published.png
  app/static/img/cloud-native-workspace/maps/map_publish_map_now.png
  app/static/img/cloud-native-workspace/maps/map_publish_updates.png
  app/static/img/cloud-native-workspace/maps/map_share_button.png
  app/static/img/cloud-native-workspace/maps/map_sharelink.png
  app/static/img/cloud-native-workspace/maps/map_sharelink_button.png
  app/static/img/cloud-native-workspace/maps/map_sharelink_copied.png
  app/static/img/cloud-native-workspace/maps/map_sharing_options_private_selected.png
  app/static/img/cloud-native-workspace/maps/map_sharing_options_public_map_developers.png
  app/static/img/cloud-native-workspace/maps/map_sharing_options_public_map_selected.png
  app/static/img/cloud-native-workspace/maps/map_sharing_options_public_map_sharelinkcopied.png
Labels: documentation
