Repository CartoDB/documentation, pull requests merged in 2022-03, with the labels that each got.

#245 Update import doc
  app/content/carto-user-manual/data-explorer/importing-data.md
  app/static/img/cloud-native-workspace/data-explorer/de_import_arrow_icon.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_existing_file.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_first_select_file.png
  app/static/img/cloud-native-workspace/data-explorer/de_import_no_permissions.png
  app/static/img/cloud-native-workspace/maps/map_widget_quickmenu_widget.png
Labels: documentation

#243 Export data doc
  app/content/carto-user-manual/_index.md
  app/content/carto-user-manual/maps/exporting-data.md
  app/content/carto-user-manual/overview/getting-started.md
  app/static/img/cloud-native-workspace/maps/map_export_data_dialog.png
  app/static/img/cloud-native-workspace/maps/map_export_data_disable.png
  app/static/img/cloud-native-workspace/maps/map_export_data_enable.png
  app/static/img/cloud-native-workspace/maps/map_export_filter_data.png
Labels: documentation

#260 Improve CARTO for Educators & FAQs style
  app/assets/scss/content.scss
  app/assets/scss/documentation.scss
  app/content/faqs/categories/analytics-toolbox.md
  app/content/faqs/categories/builder.md
  app/content/faqs/categories/carto-accounts.md
  app/content/faqs/categories/carto-for-education.md
  app/content/faqs/categories/data-observatory.md
  app/content/faqs/categories/development-tools.md
  app/content/faqs/categories/support-packages.md
  app/content/faqs/categories/workspace.md
  app/content/faqs/overview.md
Labels: documentation, enhancement, do-not-merge

#276 Add AT webinar example
  app/content/analytics-toolbox-bigquery/examples/opening-a-new-pizza-hut-location-in-honolulu.md
  app/static/img/bq-analytics-toolbox/examples/honolulu_do_subscriptions_bq.png
Labels: do-not-merge

#278 New Legend section
  app/content/carto-user-manual/maps/map-settings.md
  app/content/carto-user-manual/maps/map-styles.md
  app/static/img/cloud-native-workspace/maps/map_add_a_legend.png
  app/static/img/cloud-native-workspace/maps/map_layer_added_legend.png
  app/static/img/cloud-native-workspace/maps/map_legend_style_by_color.png
  app/static/img/cloud-native-workspace/maps/map_legend_style_by_color_radius.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_change_text_label.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_moreoptions_activated.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_moreoptions_collapsed.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_moreoptions_expanded.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_remove_from_leyend.png
  app/static/img/cloud-native-workspace/maps/map_legend_tab_revert_overrides.png
  app/static/img/cloud-native-workspace/maps/map_show_layer_panel.png
Labels: documentation

#279 New SQL panel
  app/content/carto-user-manual/maps/add-source.md
  app/static/img/cloud-native-workspace/maps/map_new_sql_panel.png
  app/static/img/cloud-native-workspace/maps/map_sql_console.png
  app/static/img/cloud-native-workspace/maps/map_sql_modal_create_table_from_query.png
  app/static/img/cloud-native-workspace/maps/map_sql_modal_create_table_from_query_OK.png
  app/static/img/cloud-native-workspace/maps/map_sql_modal_create_table_from_query_warning.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_add_query.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_cancelling_query.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_close.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_create_table_from_query.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_edited.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_enter_fullscreen.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_fullscreen.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_minimizescreen.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_run_query.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_sintax_error.png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_syntax_error(bq).png
  app/static/img/cloud-native-workspace/maps/map_sql_panel_valid_query(bq).png
  app/static/img/cloud-native-workspace/maps/map_sql_table_from_query_created.png
Labels: documentation

#178 DO-subscriptions
  app/content/carto-user-manual/_index.md
  app/content/carto-user-manual/data-explorer/introduction.md
  app/content/carto-user-manual/data-observatory/browsing-the-spatial-data-catalog.md
  app/content/carto-user-manual/data-observatory/introduction.md
  app/content/carto-user-manual/maps/add-source.md
  app/content/carto-user-manual/overview/getting-started.md
  app/content/data-observatory/_index.md
  app/content/data-observatory/guides/accessing-free-data-samples.md
  app/content/data-observatory/guides/managing-your-subscriptions.md
  app/static/img/cloud-native-workspace/data-observatory/do-access-in-bq.png
  app/static/img/cloud-native-workspace/data-observatory/do-connect-your-private-sample.png
  app/static/img/cloud-native-workspace/data-observatory/do-connect-your-sample.png
  app/static/img/cloud-native-workspace/data-observatory/do-create-tileset.png
  app/static/img/cloud-native-workspace/data-observatory/do-dataset-unsubscribe-confirm.png
  app/static/img/cloud-native-workspace/data-observatory/do-dataset-unsubscribe.png
  app/static/img/cloud-native-workspace/data-observatory/do-manage-your-subscriptions.png
  app/static/img/cloud-native-workspace/data-observatory/do-premium-confirm-subscription-request.png
  app/static/img/cloud-native-workspace/data-observatory/do-premium-request-subscription.png
  app/static/img/cloud-native-workspace/data-observatory/do-premium-subscription-request-sent.png
  app/static/img/cloud-native-workspace/data-observatory/do-premium-subscription.png
  app/static/img/cloud-native-workspace/data-observatory/do-private-access-free-sample.png
  app/static/img/cloud-native-workspace/data-observatory/do-private-sample-dataset.png
  app/static/img/cloud-native-workspace/data-observatory/do-private-sample-delete.png
  app/static/img/cloud-native-workspace/data-observatory/do-public-access-free-sample.png
  app/static/img/cloud-native-workspace/data-observatory/do-public-confirm-subscription.png
  app/static/img/cloud-native-workspace/data-observatory/do-public-subscribe-for-free.png
  app/static/img/cloud-native-workspace/data-observatory/do-public-subscription.png
  app/static/img/cloud-native-workspace/data-observatory/do-sample-dataset.png
  app/static/img/cloud-native-workspace/data-observatory/do-your-subscriptions.png
  app/static/img/cloud-native-workspace/maps/map_add_source_from_do_sample_warning_sf.png
  app/static/img/cloud-native-workspace/maps/map_add_source_from_do_select_a_connection.png
  app/static/img/cloud-native-workspace/maps/map_add_source_from_do_tree.png
Labels: documentation

#196 Geocoding content
  app/content/carto-user-manual/_index.md
  app/content/carto-user-manual/data-explorer/geocoding-data.md
  app/static/img/cloud-native-workspace/data-explorer/de_geocode_address(bq).png
  app/static/img/cloud-native-workspace/data-explorer/de_geocode_address(sf).png
  app/static/img/cloud-native-workspace/data-explorer/de_geocode_address_ok(sf).png
  app/static/img/cloud-native-workspace/data-explorer/de_geocode_data_button.png
  app/static/img/cloud-native-workspace/data-explorer/de_geocode_latitude_longitude(bq).png
Labels: documentation
